# Generated by Django 4.2.3 on 2023-07-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_edit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
