# Generated by Django 4.2.3 on 2023-07-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_data_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
